name: Build DMG
on: [push]
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Compile and Bundle App
        run: |
          mkdir -p MiniDisplay.app/Contents/MacOS
          cp Info.plist MiniDisplay.app/Contents/Info.plist
          
          SDK_PATH=$(xcrun --sdk macosx --show-sdk-path)
          
          # We link IOKit and the private DisplayServices framework
          swiftc -parse-as-library App.swift \
            -o MiniDisplay.app/Contents/MacOS/MiniDisplay \
            -sdk "$SDK_PATH" \
            -target arm64-apple-macosx11.0 \
            -framework SwiftUI \
            -framework AppKit \
            -framework IOKit \
            -F /System/Library/PrivateFrameworks \
            -framework DisplayServices
            
      - name: Create DMG
        run: |
          mkdir dist
          cp -r MiniDisplay.app dist/
          hdiutil create -volname "MiniDisplay" -srcfolder dist -ov -format UDZO MiniDisplay.app.dmg
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiniDisplay-M4-Installer
          path: MiniDisplay.app.dmg